# CRD that needs to be created first
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configs.example.io
spec:
  group: example.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
  scope: Namespaced
  names:
    plural: configs
    singular: config
    kind: Config
---
# Namespace for the custom resource
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
# Custom resource that depends on both CRD and namespace
apiVersion: example.io/v1
kind: Config
metadata:
  name: my-config
  namespace: demo
spec:
  setting: value

