run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"


