version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
  disable:
    - errcheck
    - unused
    - staticcheck
  exclusions:
    rules:
      - linters:
          - govet
        text: "composite literal uses unkeyed fields"

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

