apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: example
data:
  key: value
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: example
type: Opaque
data:
  password: cGFzc3dvcmQ=
