apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cacti.plants.example.com
spec:
  group: plants.example.com
  names:
    kind: Cactus
    listKind: CactusList
    plural: cacti  # Non-standard plural - tests DiscoverGVR!
    singular: cactus
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              height:
                type: string
              species:
                type: string
          status:
            type: object
            properties:
              phase:
                type: string
