name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Run unit tests
        run: make test
      
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Build
        run: go build -v .

  acceptance-test:
    runs-on: ubuntu-latest
    needs: [unit-test, build]
    # Only run acceptance tests on main branch pushes or same-repo PRs (to save costs)
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false
      matrix:
        terraform: ['1.6.0', '1.13.3'] 
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      
      - name: Install dependencies
        run: |
          # Install kubectl (required for oidc-setup)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          # Install K3d instead of KIND
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      
      - name: Create K3d cluster
        run: |
          # Set CI flag for Makefile
          export CI=true
          make oidc-setup

      - name: Run acceptance tests
        run: make testacc
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}

      - name: Run examples tests
        run: |
          echo "🧪 Testing examples..."
          export TF_ACC_KUBECONFIG_RAW="$(cat .testbuild/kubeconfig.yaml)"
          make test-examples
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      
      - name: Clean up K3d cluster
        if: always()
        run: k3d cluster delete k8sconnect-test || true

  acceptance-test-summary:
    name: acceptance-test
    runs-on: ubuntu-latest
    needs: acceptance-test
    if: always()
    steps:
      - name: Check matrix results
        run: |
          if [[ "${{ needs.acceptance-test.result }}" == "success" ]]; then
            echo "All acceptance tests passed"
            exit 0
          else
            echo "Some acceptance tests failed"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Run go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: --timeout=5m

