acceptance-test:
    runs-on: ubuntu-latest
    needs: [unit-test, build]
    # Only run acceptance tests on main or if PR is from the same repo (has access to secrets)
    if: github.ref == 'refs/heads/main' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false
      matrix:
        terraform: ['1.12.2']
        # Add more later
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      
      - name: Install dependencies
        run: |
          # Install kubectl (required for oidc-setup)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          # Install K3d instead of KIND
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      
      - name: Create K3d cluster
        run: |
          # Set CI flag for Makefile
          export CI=true
          make oidc-setup
      
      - name: Verify managedFields support
        run: |
          kubectl create deployment test-managed --image=nginx:1.19
          kubectl get deployment test-managed -o json | jq '.metadata.managedFields' | grep -q manager || (echo "❌ managedFields not found!" && exit 1)
          echo "✅ managedFields verified in K3d!"
          kubectl delete deployment test-managed
      
      - name: Run acceptance tests
        run: make testacc
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      
      - name: Run examples tests
        run: |
          echo "🧪 Testing examples..."
          make test-examples
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      
      - name: Clean up K3d cluster
        if: always()
        run: k3d cluster delete k8sconnect-test || true


