name: Test macOS
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
permissions:
  contents: read
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Install Docker and Kind
        run: |
          # macOS runners don't have Docker by default
          brew install --cask docker
          brew install kind kubectl
          
          # Start Docker Desktop
          open -a Docker
          
          # Wait for Docker to be ready with timeout
          echo "Waiting for Docker to start..."
          timeout=300  # 5 minutes timeout
          counter=0
          while ! docker info >/dev/null 2>&1; do
            if [ $counter -ge $timeout ]; then
              echo "Docker failed to start within $timeout seconds"
              exit 1
            fi
            echo "Waiting for Docker... ($counter/$timeout)"
            sleep 5
            counter=$((counter + 5))
          done
          echo "Docker is ready!"
      
      - name: Run acceptance tests
        run: |
          export CI=true
          make oidc-setup
          make testacc
        continue-on-error: true  # macOS Docker can be flaky in CI
      
      - name: Clean up
        if: always()
        run: k3d cluster delete --name k8sconnect-test || true

